"""empty message

Revision ID: eaad03311e58
Revises: e2996ff6a32a
Create Date: 2023-12-09 15:16:59.410217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaad03311e58'
down_revision = 'e2996ff6a32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_reply_id', 'post', ['reply_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_reply_id', type_='foreignkey')
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###
